### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by ivanvanderbyl** [ivanvanderbyl/ember-hackernews-pwa#1]
This is a non-exhaustive list of outstanding things to do before submitting a PR to HNPWA project:

### Todo:

- [x] Setup Fastboot deployment for initial content rendering before JS loads,
- [x] Fix HTTP => HTTPS redirects,
- [x] Fix colour contrast for accessibility tests,
- [x] Reduce time to the first byte of index.html,
- [x] Reduce CDN download time of vendor bundle,
- [x] Better comment styling,
- [ ] Add `/user/:id` route,
- [x] Make comment buttons bigger on mobile.

**Comment by mhadaily** [comment]
Hi @ivanvanderbyl, 
I am happy to help if you need a hand. let me know which part I can help and fix. 

I would also suggest to work on 

- [ ] Reduce render-blocking stylesheets
- [ ] Links have a discernable name.

which I am happy can take care of.

**Comment by ivanvanderbyl** [comment]
@mhadaily that'd be a big help. PRs welcome :)

**Comment by ivanvanderbyl** [comment]
@mhadaily I've created some issues I'd love some help with 😸

**Comment by mhadaily** [comment]
@ivanvanderbyl good, can you reference here. I am happy to help

**Comment by mhadaily** [comment]
@ivanvanderbyl  I saw that you worked very hard and close all the issues. is there anything that I can help this week?

**Comment by ivanvanderbyl** [comment]
@mhadaily got any experience with Fastboot? I'd like to get a fastboot deployment happening, maybe on Heroku?

**Comment by oskarrough** [comment]
@ivanvanderbyl I can configure it to deploy to now.sh ala https://github.com/oskarrough/ember-now-deployment-example if you're interested.

**Comment by ivanvanderbyl** [comment]
@oskarrough excellent idea, I'll check that out.
